UPDATE concepts SET name = 'Peaceful use of your home'          WHERE slug = 'quiet-enjoyment';
UPDATE concepts SET name = 'Right to a safe, livable home (warranty of habitability)' WHERE slug = 'habitability-standard';
UPDATE concepts SET name = 'Notice before an eviction case'     WHERE slug = 'notice-to-quit';
UPDATE concepts SET name = 'Notice before a late-rent eviction' WHERE slug = 'late-rent-notice';
UPDATE concepts SET name = 'Paying back rent can stop the case' WHERE slug = 'pay-and-stay';
UPDATE concepts SET name = 'Respond to the lawsuit and go to court' WHERE slug = 'answer-the-case';
UPDATE concepts SET name = 'Only a court can evict'             WHERE slug = 'court-eviction-only';
UPDATE concepts SET name = 'Lockouts and shutoffs are illegal'  WHERE slug = 'illegal-lockout';
UPDATE concepts SET name = 'Housing discrimination is illegal'  WHERE slug = 'fair-housing';
UPDATE concepts SET name = 'Protection from retaliation'        WHERE slug = 'retaliation-protection';
UPDATE concepts SET name = 'Rent caps and rent control'         WHERE slug = 'rent-control';
UPDATE concepts SET name = 'Written notice before an increase'  WHERE slug = 'increase-notice-period';
UPDATE concepts SET name = 'Withholding rent for repairs'       WHERE slug = 'rent-withholding';
UPDATE concepts SET name = 'Advance notice before entry'        WHERE slug = 'entry-notice-period';
UPDATE concepts SET name = 'Allowed reasons for entry'          WHERE slug = 'entry-allowed-reasons';
UPDATE concepts SET name = 'Eviction records and sealing'       WHERE slug = 'eviction-record';
UPDATE concepts SET name = 'Deposit amount cap'                 WHERE slug = 'deposit-cap';
UPDATE concepts SET name = 'Deposit receipts'                   WHERE slug = 'deposit-receipt';
UPDATE concepts SET name = 'Deposit holding and interest'       WHERE slug = 'deposit-escrow-interest';
UPDATE concepts SET name = 'Deadline to return the deposit'     WHERE slug = 'deposit-return-deadline';
UPDATE concepts SET name = 'Itemized deductions list'           WHERE slug = 'deduction-itemization';
UPDATE concepts SET name = 'Penalties for a wrongly kept deposit' WHERE slug = 'deposit-damages';
UPDATE concepts SET name = 'Reporting to a housing inspector'   WHERE slug = 'code-inspection';
