-- Restores the definitions as they stood before 000042.
UPDATE concepts SET definition = 'Your written response to an eviction lawsuit. Filing it protects your right to be heard.' WHERE slug = 'answer-the-case';
UPDATE concepts SET definition = 'When you or your landlord may change the locks.' WHERE slug = 'lock-change-rules';
UPDATE concepts SET definition = 'Asking a city inspector to check unsafe conditions in your home.' WHERE slug = 'code-inspection';
UPDATE concepts SET definition = 'A government office that takes complaints about your landlord, like a housing department or a fair housing agency.' WHERE slug = 'complaint-line';
UPDATE concepts SET definition = 'When bad conditions force you to move out, the law can treat it as if your landlord evicted you.' WHERE slug = 'constructive-eviction';
UPDATE concepts SET definition = 'Keeping photos, letters, and receipts as proof for court.' WHERE slug = 'records-and-evidence';
UPDATE concepts SET definition = 'Where your deposit must be kept, and the interest it may earn.' WHERE slug = 'deposit-escrow-interest';
UPDATE concepts SET definition = 'The penalty a landlord pays for wrongly keeping a deposit. Often 2 or 3 times the amount.' WHERE slug = 'deposit-damages';
UPDATE concepts SET definition = 'How long a landlord has to give your deposit back after you move out.' WHERE slug = 'deposit-return-deadline';
UPDATE concepts SET definition = 'A landlord may enter right away in a true emergency, like a fire or a burst pipe.' WHERE slug = 'emergency-entry';
UPDATE concepts SET definition = 'How an eviction case runs in court, from filing to hearing to the officer who carries out a removal.' WHERE slug = 'eviction-court-process';
UPDATE concepts SET definition = 'The public court record an eviction case leaves. Some places let you seal it.' WHERE slug = 'eviction-record';
UPDATE concepts SET definition = 'Laws that ban housing discrimination based on race, family status, disability, and more.' WHERE slug = 'fair-housing';
UPDATE concepts SET definition = 'Extra federal rules that protect you in public housing, with a voucher, or in other HUD assisted homes.' WHERE slug = 'federal-housing-assistance';
UPDATE concepts SET definition = 'How many days after the due date before rent counts as late.' WHERE slug = 'grace-period';
UPDATE concepts SET definition = 'Free or low cost advice from HUD approved housing counselors.' WHERE slug = 'housing-counseling';
UPDATE concepts SET definition = 'A landlord forcing you out by changing locks or cutting utilities. It is illegal.' WHERE slug = 'illegal-lockout';
UPDATE concepts SET definition = 'The written list of charges a landlord must send when keeping part of a deposit.' WHERE slug = 'deduction-itemization';
UPDATE concepts SET definition = 'What a landlord can charge when rent is late, and when the fee can start.' WHERE slug = 'late-fees';
UPDATE concepts SET definition = 'Free lawyers and legal aid for renters who qualify.' WHERE slug = 'free-legal-help';
UPDATE concepts SET definition = 'Working out a deal with your landlord through a neutral go-between, instead of or before court.' WHERE slug = 'mediation';
UPDATE concepts SET definition = 'Only a court can order you out of your home. A landlord acting alone cannot.' WHERE slug = 'court-eviction-only';
UPDATE concepts SET definition = 'How much advance warning your landlord owes you before coming in.' WHERE slug = 'entry-notice-period';
UPDATE concepts SET definition = 'A letter telling you to move out by a set date. An eviction case can only start after it.' WHERE slug = 'notice-to-quit';
UPDATE concepts SET definition = 'What happens when you pay part of the rent, or your landlord accepts a partial payment.' WHERE slug = 'partial-payments';
UPDATE concepts SET definition = 'Paying all the rent you owe to stop an eviction case. Many places allow it up to a deadline.' WHERE slug = 'pay-and-stay';
UPDATE concepts SET definition = 'The written warning you must get before a late-rent eviction case. It gives you time to pay.' WHERE slug = 'late-rent-notice';
UPDATE concepts SET definition = 'What a landlord owes you for entering illegally.' WHERE slug = 'entry-penalties';
UPDATE concepts SET definition = 'Your right to live in your home without your landlord disturbing you.' WHERE slug = 'quiet-enjoyment';
UPDATE concepts SET definition = 'Laws that cap how much rent can go up.' WHERE slug = 'rent-control';
UPDATE concepts SET definition = 'What happens to unpaid rent after you move or lose in court: collectors, credit reports, and screening reports.' WHERE slug = 'rent-debt-collection';
UPDATE concepts SET definition = 'Programs that help pay rent when money runs short.' WHERE slug = 'rent-assistance-programs';
UPDATE concepts SET definition = 'The written warning your landlord owes you before rent goes up.' WHERE slug = 'increase-notice-period';
UPDATE concepts SET definition = 'Holding back rent until your landlord fixes a serious problem. Legal only in some places.' WHERE slug = 'rent-withholding';
UPDATE concepts SET definition = 'Paying for a repair yourself and subtracting the cost from rent. Legal only in some places.' WHERE slug = 'repair-and-deduct';
UPDATE concepts SET definition = 'When a landlord punishes you for using a legal right. The law forbids it.' WHERE slug = 'retaliation-protection';
UPDATE concepts SET definition = 'The reasons the law lets your landlord enter, like repairs or showings.' WHERE slug = 'entry-allowed-reasons';
UPDATE concepts SET definition = 'Rules that limit when a utility company can shut off your water, electric, or gas, including cold and hot weather protections, and help paying the bill.' WHERE slug = 'utility-shutoff-protection';
