-- ADR-029 D2: the first-pass typing from the 2026-10-04 audit of prod, one
-- row per website host of a `nonprofit` source. Public: 211, self-help and
-- LawHelp sites, ABA Free Legal Answers, LSC, state bars. Contact first:
-- direct-service orgs. A host whose sources were typed both ways is contact
-- first. The editor corrects these on the Orgs page.
INSERT INTO help_orgs (host, name, type, updated_by) VALUES
    ('211.org', 'United Way Worldwide (211)', 'public', 'audit 2026-10-04'),
    ('211arizona.org', '211 Arizona (Solari)', 'public', 'audit 2026-10-04'),
    ('211ca.org', '211 California (United Ways of California)', 'public', 'audit 2026-10-04'),
    ('211colorado.org', '211 Colorado', 'public', 'audit 2026-10-04'),
    ('211connectsalabama.org', '211 Connects Alabama (United Ways of Alabama)', 'public', 'audit 2026-10-04'),
    ('211ct.org', '211 Connecticut / United Way of Connecticut', 'public', 'audit 2026-10-04'),
    ('211eok.org', '211 Oklahoma', 'public', 'audit 2026-10-04'),
    ('211illinois.org', '211 Illinois', 'public', 'audit 2026-10-04'),
    ('211info.org', '211info', 'public', 'audit 2026-10-04'),
    ('211iowa.org', '211 Iowa', 'public', 'audit 2026-10-04'),
    ('211kansas.org', '211 of Kansas (United Way of the Plains)', 'public', 'audit 2026-10-04'),
    ('211la.org', '211 LA', 'public', 'audit 2026-10-04'),
    ('211maine.org', '211 Maine', 'public', 'audit 2026-10-04'),
    ('211md.org', '211 Maryland', 'public', 'audit 2026-10-04'),
    ('211nh.org', '211 NH', 'public', 'audit 2026-10-04'),
    ('211nys.org', '211 New York, Inc.', 'public', 'audit 2026-10-04'),
    ('211ohio.org', 'Ohio 211', 'public', 'audit 2026-10-04'),
    ('211utah.org', '211 Utah', 'public', 'audit 2026-10-04'),
    ('211wisconsin.communityos.org', '211 Wisconsin', 'public', 'audit 2026-10-04'),
    ('603legalaid.org', '603 Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('achr.com', 'Alabama Council on Human Relations, Inc.', 'contact_first', 'audit 2026-10-04'),
    ('actionhousing.org', 'Allegheny Housing Stabilization Collaborative (Action Housing)', 'contact_first', 'audit 2026-10-04'),
    ('alabamalegalhelp.org', 'AlabamaLegalHelp.org (Legal Services Alabama)', 'public', 'audit 2026-10-04'),
    ('alsc-law.org', 'Alaska Legal Services Corporation', 'contact_first', 'audit 2026-10-04'),
    ('ardfky.org', 'AppalReD Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('arkansas211.org', 'Arkansas 211 (operated by Hark at Excellerate Foundation)', 'public', 'audit 2026-10-04'),
    ('arkansasjustice.org', 'Arkansas Access to Justice Commission', 'public', 'audit 2026-10-04'),
    ('arlawhelp.org', 'Arkansas Law Help', 'public', 'audit 2026-10-04'),
    ('arlegalaid.org', 'Legal Aid of Arkansas', 'contact_first', 'audit 2026-10-04'),
    ('assets.washingtonlawhelp.org', 'Northwest Justice Project (WashingtonLawHelp.org)', 'public', 'audit 2026-10-04'),
    ('atlantalegalaid.org', 'Atlanta Legal Aid Society', 'contact_first', 'audit 2026-10-04'),
    ('auw211.org', 'Aloha United Way 211', 'public', 'audit 2026-10-04'),
    ('avlf.org', 'Atlanta Volunteer Lawyers Foundation', 'contact_first', 'audit 2026-10-04'),
    ('az.freelegalanswers.org', 'Arizona Free Legal Answers (American Bar Association)', 'public', 'audit 2026-10-04'),
    ('azcourthelp.org', 'AZCourtHelp.org (Arizona Bar Foundation)', 'public', 'audit 2026-10-04'),
    ('azlawhelp.org', 'AZLawHelp.org', 'public', 'audit 2026-10-04'),
    ('baylegal.org', 'Bay Area Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('breadforthecity.org', 'Bread for the City', 'contact_first', 'audit 2026-10-04'),
    ('brothersredevelopment.org', 'Brothers Redevelopment Inc.', 'contact_first', 'audit 2026-10-04'),
    ('capnh.org', 'Community Action Partnership of NH', 'contact_first', 'audit 2026-10-04'),
    ('ccsww.org', 'Catholic Community Services of Western Washington', 'contact_first', 'audit 2026-10-04'),
    ('cedproject.org', 'Community Economic Defense Project', 'contact_first', 'audit 2026-10-04'),
    ('centerforjustice.org', 'Rhode Island Center for Justice', 'contact_first', 'audit 2026-10-04'),
    ('charlottelegaladvocacy.org', 'Charlotte Center for Legal Advocacy', 'contact_first', 'audit 2026-10-04'),
    ('civillawselfhelpcenter.org', 'Civil Law Self-Help Center (Legal Aid Center of Southern Nevada, with Clark County)', 'public', 'audit 2026-10-04'),
    ('clsaz.org', 'Community Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('clsphila.org', 'Community Legal Services of Philadelphia', 'contact_first', 'audit 2026-10-04'),
    ('clvu.org', 'City Life/Vida Urbana', 'contact_first', 'audit 2026-10-04'),
    ('coloradolegalservices.org', 'Colorado Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('communityactionuc.org', 'Community Action Services and Food Bank', 'contact_first', 'audit 2026-10-04'),
    ('communityadvocates.net', 'Community Advocates', 'contact_first', 'audit 2026-10-04'),
    ('communityjusticeproject.org', 'Community Justice Project', 'contact_first', 'audit 2026-10-04'),
    ('cookcountylegalaid.org', 'Cook County Legal Aid for Housing and Debt', 'contact_first', 'audit 2026-10-04'),
    ('copovertylawproject.org', 'Colorado Poverty Law Project', 'contact_first', 'audit 2026-10-04'),
    ('crla.org', 'California Rural Legal Assistance, Inc.', 'contact_first', 'audit 2026-10-04'),
    ('ctfairhousing.org', 'Connecticut Fair Housing Center', 'contact_first', 'audit 2026-10-04'),
    ('ctlawhelp.org', 'CTLawHelp.org', 'public', 'audit 2026-10-04'),
    ('cvlas.org', 'Central Virginia Legal Aid Society', 'contact_first', 'audit 2026-10-04'),
    ('dcbar.org', 'D.C. Bar Pro Bono Center', 'contact_first', 'audit 2026-10-04'),
    ('declasi.org', 'Community Legal Aid Society, Inc.', 'contact_first', 'audit 2026-10-04'),
    ('delaware211.org', 'Delaware 211', 'public', 'audit 2026-10-04'),
    ('disabilitylawcenter.org', 'Disability Law Center', 'contact_first', 'audit 2026-10-04'),
    ('disabilityrightsca.org', 'Disability Rights California', 'contact_first', 'audit 2026-10-04'),
    ('disabilityrightstx.org', 'Disability Rights Texas', 'contact_first', 'audit 2026-10-04'),
    ('disabilityrightswa.org', 'Disability Rights Washington', 'contact_first', 'audit 2026-10-04'),
    ('dnalegalservices.org', 'DNA-People''s Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('dollarenergy.org', 'Dollar Energy Fund', 'contact_first', 'audit 2026-10-04'),
    ('dpls.org', 'Dakota Plains Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('duquesnelight.com', 'Utility CAP Assistance Programs', 'contact_first', 'audit 2026-10-04'),
    ('energyoutreach.org', 'Energy Outreach Colorado', 'contact_first', 'audit 2026-10-04'),
    ('equipforequality.org', 'Equip for Equality', 'contact_first', 'audit 2026-10-04'),
    ('erlservices.org', 'East River Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('evictionhelpct.org', 'EvictionHelpCT.org (Connecticut Bar Foundation)', 'public', 'audit 2026-10-04'),
    ('fairhousingwisconsin.com', 'Metropolitan Milwaukee Fair Housing Council', 'contact_first', 'audit 2026-10-04'),
    ('fhco.org', 'Fair Housing Council of Oregon', 'contact_first', 'audit 2026-10-04'),
    ('fl211.org', 'Inform Florida (Florida 211 Network)', 'public', 'audit 2026-10-04'),
    ('floridabar.org', 'The Florida Bar', 'public', 'audit 2026-10-04'),
    ('floridalawhelp.org', 'Florida Law Help', 'public', 'audit 2026-10-04'),
    ('floridalegal.org', 'Florida Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('gbls.org', 'Greater Boston Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('georgialegalaid.org', 'GeorgiaLegalAid.org (Atlanta Legal Aid Society and Georgia Legal Services Program)', 'contact_first', 'audit 2026-10-04'),
    ('glsp.org', 'Georgia Legal Services Program', 'contact_first', 'audit 2026-10-04'),
    ('help.rentervention.com', 'Law Center for Better Housing (Rentervention)', 'public', 'audit 2026-10-04'),
    ('help4tn.org', 'Help4TN, Tennessee Alliance for Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('helpingpeople.org', 'United Way of Greater St. Louis', 'contact_first', 'audit 2026-10-04'),
    ('helplinecenter.org', 'Helpline Center', 'contact_first', 'audit 2026-10-04'),
    ('highplainsfhc.org', 'High Plains Fair Housing Center', 'contact_first', 'audit 2026-10-04'),
    ('homelinemn.org', 'HOME Line', 'contact_first', 'audit 2026-10-04'),
    ('homestart.org', 'HomeStart', 'contact_first', 'audit 2026-10-04'),
    ('housingcourtanswers.org', 'Housing Court Answers', 'contact_first', 'audit 2026-10-04'),
    ('idaholegalaid.org', 'Idaho Legal Aid Services', 'contact_first', 'audit 2026-10-04'),
    ('ifhcidaho.org', 'Intermountain Fair Housing Council', 'contact_first', 'audit 2026-10-04'),
    ('illinoislegalaid.org', 'Illinois Legal Aid Online', 'public', 'audit 2026-10-04'),
    ('indianalegalhelp.org', 'Indiana Legal Help', 'public', 'audit 2026-10-04'),
    ('iowacommunityaction.org', 'Iowa Community Action Association', 'contact_first', 'audit 2026-10-04'),
    ('iowalegalaid.org', 'Iowa Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('isba.org', 'Illinois State Bar Association', 'public', 'audit 2026-10-04'),
    ('judicare.org', 'Legal Action of Wisconsin (formerly Judicare Legal Aid)', 'contact_first', 'audit 2026-10-04'),
    ('justice4all.org', 'Legal Aid Justice Center', 'contact_first', 'audit 2026-10-04'),
    ('justmediationpgh.org', 'Just Mediation Pittsburgh', 'contact_first', 'audit 2026-10-04'),
    ('kansaslegalservices.org', 'Kansas Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('kcba.org', 'King County Bar Association', 'contact_first', 'audit 2026-10-04'),
    ('kcdrc.org', 'Dispute Resolution Center of King County', 'contact_first', 'audit 2026-10-04'),
    ('kentucky211.org', 'Kentucky 211', 'public', 'audit 2026-10-04'),
    ('klaid.org', 'Kentucky Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('kyfairhousing.org', 'Kentucky Fair Housing Council', 'contact_first', 'audit 2026-10-04'),
    ('kyjustice.org', 'Kentucky Justice Online', 'public', 'audit 2026-10-04'),
    ('la-law.org', 'Acadiana Legal Service Corporation', 'contact_first', 'audit 2026-10-04'),
    ('lablaw.org', 'Legal Aid of the Bluegrass', 'contact_first', 'audit 2026-10-04'),
    ('lacsn.org', 'Legal Aid Center of Southern Nevada', 'contact_first', 'audit 2026-10-04'),
    ('laet.org', 'Legal Aid of East Tennessee', 'contact_first', 'audit 2026-10-04'),
    ('lafairhousing.org', 'Louisiana Fair Housing Action Center', 'contact_first', 'audit 2026-10-04'),
    ('lafla.org', 'Legal Aid Foundation of Los Angeles', 'contact_first', 'audit 2026-10-04'),
    ('lanwt.org', 'Legal Aid of NorthWest Texas', 'contact_first', 'audit 2026-10-04'),
    ('las.org', 'Legal Aid Society of Middle Tennessee and the Cumberlands', 'contact_first', 'audit 2026-10-04'),
    ('lasclev.org', 'Legal Aid Society of Cleveland', 'contact_first', 'audit 2026-10-04'),
    ('laseva.org', 'Legal Aid Society of Eastern Virginia', 'contact_first', 'audit 2026-10-04'),
    ('lasoregon.org', 'Legal Aid Services of Oregon', 'contact_first', 'audit 2026-10-04'),
    ('law.cornell.edu', 'Legal Information Institute, Cornell Law School', 'public', 'audit 2026-10-04'),
    ('lawaccess.org', 'Law Access New Mexico', 'contact_first', 'audit 2026-10-04'),
    ('lawhelpmn.org', 'LawHelpMN.org (Minnesota Legal Services Coalition)', 'public', 'audit 2026-10-04'),
    ('lawhelpny.org', 'LawHelpNY (Pro Bono Net)', 'public', 'audit 2026-10-04'),
    ('lawmo.org', 'Legal Aid of Western Missouri', 'contact_first', 'audit 2026-10-04'),
    ('lawny.org', 'Legal Assistance of Western New York, Inc.', 'contact_first', 'audit 2026-10-04'),
    ('lawv.net', 'Legal Aid WV', 'contact_first', 'audit 2026-10-04'),
    ('lawyoming.org', 'Legal Aid of Wyoming', 'contact_first', 'audit 2026-10-04'),
    ('legalaction.org', 'Legal Action of Wisconsin', 'contact_first', 'audit 2026-10-04'),
    ('legalaidchicago.org', 'Legal Aid Chicago', 'contact_first', 'audit 2026-10-04'),
    ('legalaiddc.org', 'Legal Aid DC', 'contact_first', 'audit 2026-10-04'),
    ('legalaidhawaii.org', 'Legal Aid Society of Hawaii', 'contact_first', 'audit 2026-10-04'),
    ('legalaidline.org', 'Legal Aid of Western Ohio / Advocates for Basic Legal Equality', 'contact_first', 'audit 2026-10-04'),
    ('legalaidmke.com', 'Legal Aid Society of Milwaukee', 'contact_first', 'audit 2026-10-04'),
    ('legalaidnc.org', 'Legal Aid of North Carolina', 'contact_first', 'audit 2026-10-04'),
    ('legalaidnyc.org', 'The Legal Aid Society (New York City)', 'contact_first', 'audit 2026-10-04'),
    ('legalaidofnebraska.org', 'Legal Aid of Nebraska', 'contact_first', 'audit 2026-10-04'),
    ('legalaidok.org', 'Legal Aid Services of Oklahoma', 'contact_first', 'audit 2026-10-04'),
    ('legalaidworks.org', 'Legal Aid Works', 'contact_first', 'audit 2026-10-04'),
    ('legalassist.org', 'Legal Services of North Dakota', 'contact_first', 'audit 2026-10-04'),
    ('legalservicesalabama.org', 'Legal Services Alabama', 'contact_first', 'audit 2026-10-04'),
    ('lincolnlegal.org', 'Land of Lincoln Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('lonestarlegal.org', 'Lone Star Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('louisiana211.org', 'Louisiana 211 Statewide Network', 'public', 'audit 2026-10-04'),
    ('louisianalegalnavigator.org', 'Louisiana Legal Navigator', 'public', 'audit 2026-10-04'),
    ('lsc.gov', 'Legal Services Corporation', 'public', 'audit 2026-10-04'),
    ('lscd.com', 'Legal Services Corporation of Delaware, Inc.', 'contact_first', 'audit 2026-10-04'),
    ('lsem.org', 'Legal Services of Eastern Missouri', 'contact_first', 'audit 2026-10-04'),
    ('lshv.org', 'Legal Services of the Hudson Valley', 'contact_first', 'audit 2026-10-04'),
    ('lsnj.org', 'Legal Services of New Jersey', 'contact_first', 'audit 2026-10-04'),
    ('lsnjlawhotline.org', 'Legal Services of New Jersey', 'contact_first', 'audit 2026-10-04'),
    ('lsnv.org', 'Legal Services of Northern Virginia', 'contact_first', 'audit 2026-10-04'),
    ('lsny.org', 'Legal Services NYC', 'contact_first', 'audit 2026-10-04'),
    ('lsosm.org', 'Legal Services of Southern Missouri', 'contact_first', 'audit 2026-10-04'),
    ('malsi.org', 'Memphis Area Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('mass211.org', 'Mass 211', 'public', 'audit 2026-10-04'),
    ('masslegalhelp.org', 'Massachusetts Legal Help', 'public', 'audit 2026-10-04'),
    ('mdcla.org', 'Maryland Center for Legal Assistance (MCLA)', 'contact_first', 'audit 2026-10-04'),
    ('mdlab.org', 'Maryland Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('mediationcentersofhawaii.org', 'Mediation Centers of Hawaii', 'contact_first', 'audit 2026-10-04'),
    ('metcouncilonhousing.org', 'Met Council on Housing', 'contact_first', 'audit 2026-10-04'),
    ('metrohousingboston.org', 'Metro Housing Boston', 'contact_first', 'audit 2026-10-04'),
    ('mi211.org', 'Michigan 211', 'public', 'audit 2026-10-04'),
    ('michiganlegalhelp.org', 'Michigan Legal Help', 'public', 'audit 2026-10-04'),
    ('mmls.org', 'Mid-Missouri Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('montana211.org', 'Montana 211', 'public', 'audit 2026-10-04'),
    ('montanafairhousing.org', 'Montana Fair Housing', 'contact_first', 'audit 2026-10-04'),
    ('montanalawhelp.org', 'Montana Legal Services Association', 'contact_first', 'audit 2026-10-04'),
    ('motenanthelp.org', 'Missouri Tenant Help', 'public', 'audit 2026-10-04'),
    ('ms.freelegalanswers.org', 'Mississippi Free Legal Answers (American Bar Association)', 'public', 'audit 2026-10-04'),
    ('msatjc.org', 'Mississippi Access to Justice Commission', 'public', 'audit 2026-10-04'),
    ('mscenterforjustice.org', 'Mississippi Center for Justice', 'contact_first', 'audit 2026-10-04'),
    ('mslegalservices.org', 'MSLegalServices.org', 'contact_first', 'audit 2026-10-04'),
    ('mtlsa.org', 'Montana Legal Services Association', 'contact_first', 'audit 2026-10-04'),
    ('mvlslaw.org', 'Maryland Volunteer Lawyers Service', 'contact_first', 'audit 2026-10-04'),
    ('myfirstlink.org', 'FirstLink', 'contact_first', 'audit 2026-10-04'),
    ('mylegalaid.org', 'Mid-Minnesota Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('myunitedway.com', 'United Way of the Capital Area', 'public', 'audit 2026-10-04'),
    ('nc211.org', 'NC 211 (United Way of North Carolina)', 'public', 'audit 2026-10-04'),
    ('nd.freelegalanswers.org', 'ABA Free Legal Answers, North Dakota', 'public', 'audit 2026-10-04'),
    ('ne211.org', '211 Nebraska', 'public', 'audit 2026-10-04'),
    ('needhelppayingbills.com', 'Jon McNamara', 'contact_first', 'audit 2026-10-04'),
    ('nevada211.org', 'Nevada 211', 'public', 'audit 2026-10-04'),
    ('nevadalegalservices.org', 'Nevada Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('newmexicolegalaid.org', 'New Mexico Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('nhla.org', 'New Hampshire Legal Assistance', 'contact_first', 'audit 2026-10-04'),
    ('nj211.org', 'NJ 211', 'public', 'audit 2026-10-04'),
    ('nlihc.org', 'National Low Income Housing Coalition', 'public', 'audit 2026-10-04'),
    ('nlsa.us', 'Neighborhood Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('nlsp.org', 'Neighborhood Legal Services Program', 'contact_first', 'audit 2026-10-04'),
    ('nmceh.org', 'New Mexico Coalition to End Homelessness', 'contact_first', 'audit 2026-10-04'),
    ('nnlegalaid.org', 'Northern Nevada Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('nvrural.org', 'Nevada Rural Housing Authority', 'contact_first', 'audit 2026-10-04'),
    ('oacaa.org', 'Ohio Association of Community Action Agencies', 'contact_first', 'audit 2026-10-04'),
    ('ohiolegalhelp.org', 'Ohio Legal Help', 'public', 'audit 2026-10-04'),
    ('okaccesstojustice.org', 'Oklahoma Access to Justice Foundation', 'public', 'audit 2026-10-04'),
    ('okbar.org', 'Oklahoma Bar Association', 'public', 'audit 2026-10-04'),
    ('oklahoma.freelegalanswers.org', 'Oklahoma Free Legal Answers (American Bar Association)', 'public', 'audit 2026-10-04'),
    ('oregonlawcenter.org', 'Oregon Law Center', 'contact_first', 'audit 2026-10-04'),
    ('oregonlawhelp.org', 'Oregon Law Help (Oregon State Bar)', 'public', 'audit 2026-10-04'),
    ('osbar.org', 'Oregon State Bar', 'public', 'audit 2026-10-04'),
    ('pa.gov', 'Allegheny County Assistance Office', 'contact_first', 'audit 2026-10-04'),
    ('pa211.org', 'PA 211 (United Way of Pennsylvania)', 'public', 'audit 2026-10-04'),
    ('pa211sw.org', 'PA 211 Southwest', 'public', 'audit 2026-10-04'),
    ('palawhelp.org', 'Pennsylvania Legal Aid Network', 'public', 'audit 2026-10-04'),
    ('palegalaid.net', 'Pennsylvania Legal Aid Network', 'contact_first', 'audit 2026-10-04'),
    ('phillytenant.org', 'PhillyTenant.org', 'contact_first', 'audit 2026-10-04'),
    ('pisgahlegal.org', 'Pisgah Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('probonomd.org', 'Pro Bono Resource Center of Maryland', 'contact_first', 'audit 2026-10-04'),
    ('pslegal.org', 'Prairie State Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('ptla.org', 'Pine Tree Legal Assistance', 'contact_first', 'audit 2026-10-04'),
    ('renters.equalhousing.org', 'Housing Equality Center of Pennsylvania', 'contact_first', 'audit 2026-10-04'),
    ('rentervention.com', 'Rentervention / Law Center for Better Housing', 'public', 'audit 2026-10-04'),
    ('renthelppghresources.org', 'RentHelpPGH', 'contact_first', 'audit 2026-10-04'),
    ('resources.sc211.org', 'United Way Association of South Carolina (SC 211)', 'public', 'audit 2026-10-04'),
    ('rils.org', 'Rhode Island Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('rturn.net', 'Tenant Union Representative Network (TURN)', 'contact_first', 'audit 2026-10-04'),
    ('sazlegalaid.org', 'Southern Arizona Legal Aid', 'contact_first', 'audit 2026-10-04'),
    ('sbnm.org', 'State Bar of New Mexico Foundation', 'public', 'audit 2026-10-04'),
    ('sc.freelegalanswers.org', 'South Carolina Free Legal Answers (ABA)', 'public', 'audit 2026-10-04'),
    ('sc211.org', 'United Way Association of South Carolina (SC 211)', 'public', 'audit 2026-10-04'),
    ('schousinglaw.org', 'South Carolina Legal Services Housing Law Center', 'contact_first', 'audit 2026-10-04'),
    ('scjustice.org', 'South Carolina Appleseed Legal Justice Center', 'contact_first', 'audit 2026-10-04'),
    ('sclegal.org', 'South Carolina Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('sclonm.org', 'Senior Citizens Law Office, Inc.', 'contact_first', 'audit 2026-10-04'),
    ('seniorlawcenter.org', 'SeniorLAW Center', 'contact_first', 'audit 2026-10-04'),
    ('sites.lawschool.cornell.edu', 'Cornell Law School Tenants Advocacy Program', 'contact_first', 'audit 2026-10-04'),
    ('slls.org', 'Southeast Louisiana Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('slsct.org', 'Statewide Legal Services of Connecticut', 'contact_first', 'audit 2026-10-04'),
    ('solid-ground.org', 'Solid Ground', 'contact_first', 'audit 2026-10-04'),
    ('ssfhc.org', 'Silver State Fair Housing Council', 'contact_first', 'audit 2026-10-04'),
    ('stayhousedla.org', 'Stay Housed LA', 'contact_first', 'audit 2026-10-04'),
    ('svlas.org', 'Southwest Virginia Legal Aid Society', 'contact_first', 'audit 2026-10-04'),
    ('tenantresourcecenter.org', 'Tenant Resource Center', 'contact_first', 'audit 2026-10-04'),
    ('tenants-rights.org', 'Metropolitan Tenants Organization', 'contact_first', 'audit 2026-10-04'),
    ('tenantsunion.org', 'Tenants Union of Washington State', 'contact_first', 'audit 2026-10-04'),
    ('texasbar.com', 'State Bar of Texas', 'public', 'audit 2026-10-04'),
    ('texaslawhelp.org', 'TexasLawHelp.org', 'public', 'audit 2026-10-04'),
    ('texastenant.org', 'Texas Tenant Advisor (Texas Housers)', 'public', 'audit 2026-10-04'),
    ('tlsc.org', 'Texas Legal Services Center', 'contact_first', 'audit 2026-10-04'),
    ('trla.org', 'Austin Tenants Council', 'contact_first', 'audit 2026-10-04'),
    ('unitedwayatlanta.org', 'United Way of Greater Atlanta', 'public', 'audit 2026-10-04'),
    ('utahdisputeresolution.org', 'Utah Dispute Resolution', 'contact_first', 'audit 2026-10-04'),
    ('utahlegalservices.org', 'Utah Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('uwncnm.org', 'United Way of North Central New Mexico', 'public', 'audit 2026-10-04'),
    ('uwri.org', 'United Way of Rhode Island', 'contact_first', 'audit 2026-10-04'),
    ('vermont211.org', 'Vermont 211, United Ways of Vermont', 'public', 'audit 2026-10-04'),
    ('vlnmn.org', 'Volunteer Lawyers Network', 'contact_first', 'audit 2026-10-04'),
    ('vlpnet.org', 'Volunteer Lawyers Project', 'contact_first', 'audit 2026-10-04'),
    ('vlsoct.org', 'Volunteer Legal Services of Central Texas', 'contact_first', 'audit 2026-10-04'),
    ('vtlawhelp.org', 'VTLawHelp.org', 'contact_first', 'audit 2026-10-04'),
    ('wa211.org', 'Washington 211', 'public', 'audit 2026-10-04'),
    ('washingtonlawhelp.org', 'Northwest Justice Project (WashingtonLawHelp.org)', 'public', 'audit 2026-10-04'),
    ('wislawhelp.org', 'Wisconsin Law Help', 'public', 'audit 2026-10-04'),
    ('wtls.org', 'West Tennessee Legal Services', 'contact_first', 'audit 2026-10-04'),
    ('yourlegalaid.org', 'Legal Aid Society', 'contact_first', 'audit 2026-10-04')
ON CONFLICT (host) DO NOTHING;
