# fly.toml app configuration file generated for defensiverenting on 2026-04-26T05:46:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'defensiverenting'
primary_region = 'ewr'

[build]

[env]
  ENV = 'production'
  LISTEN_ADDR = ':8080'
  LOG_LEVEL = 'info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 150

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/readyz'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[metrics]]
  port = 9091
  path = '/metrics'
