name: Deploy main site

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy main site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --config fly.toml --app defensiverenting --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_MAIN_DEPLOY_TOKEN }}
